#use postgres/example as user/password
version: '1.0'
nodePort: 3000

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
  
  adminer:
    image: adminer
    restart: always
    ports:
     - 8080:8080
